### ISSUE TITLE
Empty value1,2 and 3 at action/control/condition levels if not needed (to avoid failing decode)

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-core#2038]
Hi,

we found a strange situation.
We had a condition on an action that we don't wanna use it anymore.

**Before:**
![image](https://user-images.githubusercontent.com/14328346/68853374-c322f100-06d1-11ea-9818-26668432b7ab.png)

So we ignore the conditions to compare and set the condition to be exectuted always.

**Now:**
![image](https://user-images.githubusercontent.com/14328346/68853433-e3eb4680-06d1-11ea-80f2-55a5bcd829e2.png)

Besides condition is set to "always" cerberus is trying to compare "Condition Value1" and "Condition Value2".

![image](https://user-images.githubusercontent.com/14328346/68853522-1137f480-06d2-11ea-87e4-817b724087f4.png)

Is this expected?
It is a strange situation because on "always" condition we cannot set value1 or value2 but Cerberus seems to be trying to use the old values.

Can you please take a look and clarify?

Cerberus4.4-SNAPSHOT-1440 in prd 

Thanks!

**Comment by cDelage** [comment]
Cerberus will not use your old values, 
It stock parameters values, but it don't take in consideration this.
It's not clean to display it in my opinion, but it not impact your test.

**Comment by RobertoAbraul** [comment]
Hi @cDelage ,

as you can see in my image it fails when I leave the old values in "always" condition.
Test case/action is only ok after remove the old values.

Thanks

**Comment by vertigo17** [comment]
@RobertoAbraul , what happen here is that even if 'always' condition does not require any parameter, parameters are still defined in the database and Cerberus tries to decode them. Decode error consequently still raise.
This is not a good behaviour and deserve a fix.
What we will do is leave the parameters defined (so that in case you change back the operator, you don't have to key them again) but empty them at execution level when not required so that it does not get decoded.

**Comment by vertigo17** [comment]
As a workaround you can of course empty them by temporary changing the operator.

**Comment by ittaLaRedoute** [comment]
Hi @vertigo17 any news on that ?
