### ISSUE TITLE
[Cerberus4.13] Support timeout overwrite for Appium (IPA and APK) applications.

### ISSUE THREAD

**Issue by akatmiranda** [cerberustesting/cerberus-core#2331]
On 4.13 it is possible to set a timeout for a specific step (new functionality). It is not working. The value inserted is not respected, timeout is inherited from general definition of testcase execution/campaign.

Please refer to images:

![SetTimeout](https://user-images.githubusercontent.com/38046035/145577496-7d4f39e9-f66e-4fd0-b8e1-f84c3348baad.png)
![SetTimeout_Not](https://user-images.githubusercontent.com/38046035/145577500-29d622e4-1d2c-45ff-9540-e37471998fc0.png)

**Comment by vertigo17** [comment]
Hello @akatmiranda. Sorry but we could not reproduce.
It is working on the test I just made using BrowserStack.
Can you please detail or reproduce using prod.cerberus-testing ?

**Comment by vertigo17** [comment]
This is an example taken on latest version:

With a timeout parameter to 15000 (not overwrite):

![image](https://user-images.githubusercontent.com/5342048/145713116-dcc99a73-c636-405c-99b9-4cc7240b36df.png)

![image](https://user-images.githubusercontent.com/5342048/145713187-250320aa-630a-4197-bb58-63629947104d.png)

**Result:**

![image](https://user-images.githubusercontent.com/5342048/145713143-92763975-1fcf-4417-874d-07e616f54d8b.png)

With the overwrite parameter to 5000:

![image](https://user-images.githubusercontent.com/5342048/145713444-5fe271e5-486c-41b0-ba3f-5f653c64bb2c.png)

![image](https://user-images.githubusercontent.com/5342048/145713226-0db55066-26f3-4a2d-90dc-07257d98c48e.png)

**Result:**

![image](https://user-images.githubusercontent.com/5342048/145713256-85454a50-d382-45e6-bb82-a7f726a587af.png)

Maybe you forgot to save the script after changing the overwrite options.
We changed the confirmation button from Save to OK in order to make it easier to understand that you need to save the testcase in order to apply the new settings.

**Comment by vertigo17** [comment]
Any news ?

**Comment by ffazendeiro** [comment]
Hi @vertigo17 ,
We created the test on [cerberus-testing.com](https://prod.cerberus-testing.com/TestCaseScript.jsp?test=LaRedoute&testcase=0001A) and we got the same result, seems that for the mobile applications the timeout is not being overwritten when below defined timeout.
I we define a timeout above the one defined, it seem to add them...
Please check execution: https://prod.cerberus-testing.com/TestCaseExecution.jsp?executionId=396860
Maybe we are missing some configurations :(

All seems ok on our end for Web applications (timeout overwrite correctly applied).
