### ISSUE TITLE
[LR] particular REST service not working

### ISSUE THREAD

**Issue by hananema** [cerberustesting/cerberus-core#2383]
Hello,

I cannot succeed to call a REST service that has the following particularity:
- Content-Type=multipart/form-data
![image](https://user-images.githubusercontent.com/41586025/166681269-97a0df8d-42ed-4d12-a526-81ecee5f6846.png)

- Request in Request detail
![image](https://user-images.githubusercontent.com/41586025/166681182-3ef2f0ae-b212-4150-9198-6aff53d12927.png)

The call works from Postman and is done as following:
<img width="642" alt="image" src="https://user-images.githubusercontent.com/41586025/166681825-33a37bee-77f8-4c47-b9f9-d941b07259d7.png">

The call works from the swagger and is done as the following:

![image](https://user-images.githubusercontent.com/41586025/166682955-20bc1488-9a51-4315-b450-58d2436969c9.png)

Can you please help?

Please let me know if you need more information.

Regards,

Hanane

**Comment by vertigo17** [comment]
Do you have an endpoint available that we can test ?

**Comment by hananema** [comment]
Hello,
No I don't have any, but I will check if I can find one.

**Comment by hananema** [comment]
Hello,
I searched for an endpoint, but did not succeed to find any.

**Comment by vertigo17** [comment]
Did you try to feed the json in -F parameter inside Request tab et clean Request Detail tab.
Can you provide the trace of the call 'Service Call' JSON file in order to see the error message ?
What is the expected answer ? Answer coming from postman as it works.

**Comment by ittaLaRedoute** [comment]
Hello @vertigo17 
I did the test with the json in -F parameter inside Request tab but I got the same error:
![image](https://github.com/cerberustesting/cerberus-core/assets/97182913/a98e42ab-c0e5-4580-bd75-fd1517069fea)
"errorDescription": "[org.springframework.web.multipart.MultipartException] Failed to parse multipart servlet request; nested exception is java.io.IOException: org.apache.tomcat.util.http.fileupload.FileUploadException: the request was rejected because no multipart boundary was found",

**Comment by ittaLaRedoute** [comment]
This issue also blocks us on another campaign.
We want to test a Mirakl API that does an import of a file into Mirakl.
Here are the details of the call and the error on Cerberus:
With Postman:
![image](https://github.com/cerberustesting/cerberus-core/assets/97182913/01bf4837-33d5-4cb8-9530-b58ee9e70d59)
![image](https://github.com/cerberustesting/cerberus-core/assets/97182913/b27b5690-be7c-4c1a-913e-8b9a0cb4fb2a)

With Cerberus, I tried with the content of the file in the request and the shop in request details, I have this error:
`{
   "status":400,
   "message":"Failed to parse multipart servlet request; nested exception is org.apache.tomcat.util.http.fileupload.FileUploadException: the request was rejected because no multipart boundary was found"
}`
Thank you for your help!

**Comment by vertigo17** [comment]
Hello @hananema 
With @MathisSenicourt we would like to propose you a quick fix in order to unlock you on that test with that spec:

If you **add [form-data] text anywhere the service description**, you would activate the call in multipart format.

The request detail would have the following format :
![image](https://github.com/cerberustesting/cerberus-core/assets/5342048/d891a4c6-7611-4097-909a-42c6f44246f7)
the format for the files would be **@ followed by the path to the file (inside Cerberus server)**.
Could that work for you ? Do you have access to Cerberus server in order to upload the xml files ?

Later, we would add at service level a select box in order to select in a clean way the 'form-data' option + Allow the file to be uploaded inside Cerberus (similar to application object).
Then, instead of putting @/home/seluser/test.xml that would be: @%object.MYFILE.filename%

**Comment by ittaLaRedoute** [comment]
Hello @vertigo17 
Yes  we do have access to Cerberus server to upload xml files, so that could work for us.
Thanks alot
Hanane

**Comment by vertigo17** [comment]
last comit https://github.com/cerberustesting/cerberus-core/commit/6a9a0ecef793163d416544e4373b966c874c394d
should fix the issue.
As a reminder:
1/ Description of the service should include [form-data]
![image](https://github.com/cerberustesting/cerberus-core/assets/5342048/4b82e58d-9ef5-43b4-be18-d57e95cd2e52)

2/ Header must not include the 'Content-Type'. Either by unactivating it or not adding it.
![image](https://github.com/cerberustesting/cerberus-core/assets/5342048/e1f5d977-46d5-4aaf-bcd0-0b3cee987810)


3/ Format of the request detail
![image](https://github.com/cerberustesting/cerberus-core/assets/5342048/8b383649-0312-41eb-9aaf-f048b3b807e3)

Please confirm the fix work so that we can proceed to a cleaner fix.
