### ISSUE TITLE
Kafka producer - avro schema key+value update wanted

### ISSUE THREAD

**Issue by jmlecul** [cerberustesting/cerberus-core#2418]
Cerberus Version : 4.15-1742

Hi, 
With the recent update we can write kafka event with avro schema value (and a key in string),
But we have kafka topic with both avro schema for value and key, example :
![image](https://user-images.githubusercontent.com/114755928/200861244-3d9019d1-b75a-4f6a-b439-2c112a05ef39.png)

in this cas the key is also drived with an other avro schema (diffrent from the value one)

but the service screen don't allow this kind of double avro schema : 
![image](https://user-images.githubusercontent.com/114755928/200861025-5a7268e7-da12-40ea-9407-1df4a27ef1c2.png)

Thanx in advance for this request, no doubt than it will finalize the kafka avro schema integration in cerberus

regards,
jm

**Comment by vertigo17** [comment]
Hello @jmlecul my last commit should fix the issue.
An additional field was added to save the schema for the key.
Schema are mandatory when using PRODUCE method. Schema registry will then be activated only if corresponding schema is defined (not empty).
When using SEARCH method, you also have to define a non empty value in order to activate key avro deserialisation. The value does not matter as long as it is not empty.

Unfortunately this is so far not possible for me to test so I really will need your feedback in order to confirm that this code is working fine and introduce no regression.
I was only able to test the KAFKA without use of Avro that still work fine.

**Comment by vertigo17** [comment]
Hello again. I finaly managed to test on my side using a confluence docker compose. 
I was able to perform quite a few fix and secure to test all produce and search using either key or value (or both) in avro format. 
modal has been redesigned also adding 2 checkbox in order to activate avro on either of the 2 fields. 
I let you confirm everything is fine on your side.
