### ISSUE TITLE
 Test case with an upload (following #1303 )

### ISSUE THREAD

**Issue by Kevin-Sinapayen** [cerberustesting/cerberus-core#2473]
Hello,

This is a question rather than an issue.

I found this reply on https://github.com/cerberustesting/cerberus-core/issues/1303

![image](https://github.com/cerberustesting/cerberus-core/assets/139990094/aaff56c6-3fd1-459d-a370-d65f046ffe57)

And I have a question about where to find the PDF files.
I'm currently using the free SaaS version of Cerberus for a POC, so I don't have any access to the filesystem.
How can I use PDF samples? I need PDF files that are stored directly on the Cerberus server.

I tried:
Unix : /home/seluser/Downloads/mySample.pdf
Windows : C:/Data/CerberusFiles/mySample.pdf

But it doesn't work, these files don't exist.

Thanks for your help.

**Comment by vertigo17** [comment]
Hello,
I am not sure what you want to achieve.
If you want to test an upload a file on your application, the best way to perform that is to 

1/ Upload the file to the robot side in order to make it available from the Downloads folder.
In order to do that, you need to use the uploadRobot action specifying the path where the file need to be (ex : /home/seluser/Downloads/mySample.pdf), the content of the file needs to be specified in base64 format. For that you need to convert your file to base64.

2/ From your Application/Website, move to the corresponding screen or button and open the browser dialogue box that will ask to choose the file to upload.

3/ Double click on the Downloads Folder (using doubleclik action with picture= element pointing to the Downloads image folder)

4/ Double click on the mySample.pdf file (still using doubleclik action with picture= pointing to the mySample.pdf file image)

5/ Once the file is uploaded to your application you can control your application/web site expected behaviour.

If you want to test the download of a file from your application, you should

1/  Clean the Robot download folder from any previous files that could still be there.
Use the cleanRobotFile action with  /home/seluser/Downloads/ folder in order to empty it.

2/ Browse on your application/Website until you get to the download button / action and trigger the downloads

3/ use the getRobotFile action with /home/seluser/Downloads/* or any other string that match the files that should be downloaded.
The action will report a jsonfile with detail of the files found on the corresponding folder.
You can then control the size, name, time of the file created.
If the file is json or xml you can also control the content of it.

We can help you configure an example so that you can better understand.

UploadRobotFile and GetRobotFile actions prevent you from having to access the local FS. More than that it secure the file is always there wherever the execution occurs.
Using CleanRobotFile also secure that the file is alone in its folder so that the image recognition feature will always find it for doubleclick.

**Comment by Kevin-Sinapayen** [comment]
Hello,

Thank you, yes I need to upload a file on my application.
I can't use the Upload robot file action.

![image](https://github.com/cerberustesting/cerberus-core/assets/139990094/1cc64d01-286e-49fa-909b-d23b0a565e8f)

![image](https://github.com/cerberustesting/cerberus-core/assets/139990094/8a57ecac-8314-4bc1-bd0c-70368b7e5d90)

**Comment by vertigo17** [comment]
Those actions are not selenium native and require cerberus robot extention to work. 
unfortunatly, browserstack does not include that extention. 
You will have to use a supported cerberus robot. 
BTW, this is also the same for image recognition feature.

**Comment by Kevin-Sinapayen** [comment]
Hi,
I am currently using the free SaaS version of Cerberus
I can only choose one of these robots
![image](https://github.com/cerberustesting/cerberus-core/assets/139990094/94793e33-e3e5-4b00-8602-5740f7b33ab1)

**Comment by vertigo17** [comment]
You should pick only the CerberusChrome or CerberusChromeProxy.
Browserstack* robots are using Browserstack service (https://www.browserstack.com/). They allow to run on many different OS and browsers but don't have the features of upload/Download files, image regognition and network traffics controls that are provided by cerberus-robot-extention and only integrated with our robots.

**Comment by Kevin-Sinapayen** [comment]
It worked with CerberusChromeProxy
Thank you!
