### ISSUE TITLE
[LR][kafka service][header filter] we are not able to use header filter and event filter together

### ISSUE THREAD

**Issue by ittaLaRedoute** [cerberustesting/cerberus-core#2488]
Hello,

We have a kafka service that uses Event filter and we want to add a Header filter in order to find exactly the event we want.
This didn't work. The properties inside the header filter were not calculated. We suspect that each filter works separatly, but can't be used together.

Can you please help?

here is a screenshot of the result:
![image](https://github.com/cerberustesting/cerberus-core/assets/97182913/a00b4de3-b935-491d-87f7-1dc8bd661e49)

Thank you in advance.

**Comment by vertigo17** [comment]
I can confirm that both filters can be used at the same time.
They will act like a & (both filter must match in order for the event to be selected).
The debug JSON message in screenshot was not decoded. That has been fixed recently.
Maybe you can test with an earlier version at least to get the correct value and check that criteria works.
If necessary, we can make an example on prod.cerberus-testing.com in order to confirm the behaviour.

**Comment by ittaLaRedoute** [comment]
Hello, we've done the test on version Cerberus4.17-SNAPSHOT-1756 Build 20231016-203745 and it does work. properties are calculated.
Thank you
