### ISSUE TITLE
Robot froze

### ISSUE THREAD

**Issue by Kevin-Sinapayen** [cerberustesting/cerberus-core#2505]
Cerberus Version : 4.16-1747

Hi, is there anything I can do to unlock the executions when they freeze

They stay like this for hours

![image](https://github.com/cerberustesting/cerberus-core/assets/139990094/1063a402-c74b-4522-9abf-f4db1432fef3)

And then I get this error

![image](https://github.com/cerberustesting/cerberus-core/assets/139990094/2ebd32f1-f4c1-4ef3-a5a5-11f8b56f712b)

**Comment by Kevin-Sinapayen** [comment]
@vertigo17 please this is urgent, I have a demonstration tomorrow (nov30th) to make the QAs love Cerberus :)

**Comment by vertigo17** [comment]
I will check that later making sure it is fixed tomorrow morning.

**Comment by vertigo17** [comment]
mutualised infra was overloaded. I added a bit of ressources in order to support the load.
I also fixed your test case: OBQ / CT002 changing some xpath from:

//*[@id="login-connect-button"] 
to
//*[text()='Se connecter']

//*[@id="email-label"]
to
//input[@id="email"]

At the end of your test, I also clicked on the caracterisation menu button and removed the wait action that was useless.

https://citeo.app.cerberus-testing.com/TestCaseExecution.jsp?executionId=10331

**Comment by Kevin-Sinapayen** [comment]
Thank you @vertigo17 it works! You're the best
