### ISSUE TITLE
Error in create environment

### ISSUE THREAD

**Issue by cencio91** [cerberustesting/cerberus-core#2536]
Cerberus Version : 4.18-1783

Hi, I'm trying to create an environment, but I get this error
![immagine](https://github.com/user-attachments/assets/ed23b0f4-f6eb-49a6-879a-91f570efadf0)

The first time i've tried to insert it, the error wasn't shown, but the environment row was not created in the table. All next attempts gives me this error.

The IT Country is defined as:

| idname | value | attribute | attribute 2
| ---- | ---- | ---- | ---- |
| COUNTRY | Italiano | | it |

The system is defined as:

| idname | value |
| ---- | ---- |
| SYSTEM | xxxxxxx |

thank you for your support

**Comment by vertigo17** [comment]
Hello.
It is probably that record is really inserted but not displayed on the environment list page due to system combo filtering.
Did you check that the system combo include the system where you created the record ?

To be sure, connect using an admin account and select all systems from header combo.
I am pretty sure you will see your environement.

NB : I Suppose your country invariant value is IT and not  Italiano that I beleive is the description.

**Comment by cencio91** [comment]
Hi Vertigo,

thank you very much for your support. 

You are right, i must check the new system from the dropdown in the header. After doing this, I can see my inserted record.

As reference for other users, the dropdown is here:
![immagine](https://github.com/user-attachments/assets/1faf6222-2d70-400b-82f2-7e88871cc845)

just two usability suggestions:
- It would be more user friendly if a new added system will be selected by default in that filter.
- Also, it's strange that if I add a system as admin, my admin user hasn't that system assigned by default in user management

Thank you very much, we can close this issue.
Have a nice day
