### ISSUE TITLE
Documentation] How to pass a property to library?

### ISSUE THREAD

**Issue by cencio91** [cerberustesting/cerberus-core#2548]
Hi,
I wonder How to pass a property to an action that is marked as library.

For example, my reusable action "login" could be used in different test case, and based on test requirements, 
it should be called with a different property "username" so I can choose to login as admin, user ecc.

How to accomplish this?

thank you very much

**Comment by vertigo17** [comment]
Hello @cencio91 , in order to achieve that I would more suggest the following:
A login step that include the action to type %property.LOGIN% to the corresponding field + all other necessary actions in order to login. That step should be marked as library.
On that test case you can define the default value for property LOGIN to _user_.

On a first test case that need to login with _user_, you just need to link the library step with no changes. The property will be inherited from the original value.

On a second testcase that need admin login, you can still link the same library step.
On top of that, just add to that specific test case the same property LOGIN with the value _admin_. That value will overwrite the original value defined from the library.

Same mecanism can be used with password and any other property.

NB:
If you want to secure pass at execution level you can name your property so that it contains _PASSW_. ex PASSWORD
If you want to secure it everywhere, put it in a datalib and flag it as encrypted.

**Comment by vertigo17** [comment]
Some documentation could help you:

https://qa.cerberus-testing.com/documentation/D1/documentation_en.html#_test_case_property

https://qa.cerberus-testing.com/documentation/D1/documentation_en.html#_test_case_variables

**Comment by cencio91** [comment]
Hi vertigo, thank you very much for your comphrensive explaination. From documentation I missed the parameter override, but now it's clear.

I wish you a nice day,
Francesco
