### ISSUE TITLE
Unable to delete a test in QUWITHDEP status from queue

### ISSUE THREAD

**Issue by cencio91** [cerberustesting/cerberus-core#2555]
Hi,

My final goal was to define a dependency between tests to run them in the right order in the Test case (for example, create an elemant and delete it after). Since there isn't a way to set dependencies at Test Set level, I've added one in the Test Header "dependency" options.
![immagine](https://github.com/user-attachments/assets/258be260-78f8-4879-89e0-d57ad23dddc0)

When I've clicked on "run" for a test that has a dependency, it has gone in QUWITHDEP status.

If I've tried to delete it from TestCaseExecutionQueueList page, but I got the following error:
![immagine](https://github.com/user-attachments/assets/a1f83518-02c7-4e8b-b747-03f082efcd10)

The TestCase field seem to be invalid, but it's the right name of the test (and no one field is editable)

My version is Cerberus4.19-SNAPSHOT-1858 Build 20241022-135950 in prd

Thank you very much for tour support

**Comment by vertigo17** [comment]
I made a small fix that allow to edit the queue entry when in QUWITHDEP status.

NB : since a few commit, if you submit an execution with a dependency that is not already existing in the corresponding tag, the dependencies will be IGNORED.
They will appear like that:

![image](https://github.com/user-attachments/assets/18e3e7ea-b6ad-434f-8d10-753c7cf7da5e)

If you "Save and Submit" the execution it will be released.
